version: '3.8'
services:
  events-microservice:
    ports:
      - "6001:443"
      - "6000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ASPNETCORE_URLS=https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=6001
      - Consul__Host=consul
      - ConnectionStrings__ConnectionString=Server=events;Username=postgres;Password=pass;Database=entre2ages;Port=5431

  users-microservice:
    ports:
      - "5001:443"
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ASPNETCORE_URLS=https://+;http://+"
      - ConnectionStrings__ConnectionString=Server=users;Username=postgres;Password=pass;Database=entre2ages;Port=5432
      - Consul__Host=consul
      - ASPNETCORE_HTTPS_PORT=5001

  messages-service:
    ports:
      - "4000:443"
      - "4000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ASPNETCORE_URLS=https://+;http://+"
      - MongoDatabaseSettings__ConnectionString=mongodb://messages
      - Consul__Host=consul
      - ASPNETCORE_HTTPS_PORT=4001

  gateway:
    ports:
      - "9001:443"
      - "9000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ASPNETCORE_URLS=https://+;http://+"
      - ASPNETCORE_HTTPS_PORT=9001
      - GlobalConfiguration__ServiceDiscoveryProvider__Host=consul
  rabbitmq:
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - 'RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error}]'

  events:
    ports:
      - 5431:5432

  users:
    ports:
      - 5432:5432

  messages:
    ports:
      - 27015:27017

  consul:
    ports:
      - 8500:8500
