name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Restore, Build and Test
      shell: bash
      run: |
        for sln in $(find . -name '*.sln'); do
          echo "Processing $sln"
          dotnet restore "$sln"
          dotnet build "$sln" --no-restore
          dotnet test "$sln" --no-build --verbosity normal
        done
